name: job_1

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: actions/setup-python@v4
      - run: python --version
