name: job_1

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: actions/setup-python@v4
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry install -C ./job_1 
      - run: poetry run -C ./job_1 python -m job_1.main
        env: 
          - SOME_ENV_VAR: HELLO
          - SOME_SECRET_ENV_VAR: ${{ secrets.SOME_SECRET_ENV_VAR }}
